# This is a basic workflow to help you get started with Actions

name: manual

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the trunk branch
on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'a greeting'
        default: 'hi'
      name:
        description: 'a name'
        required: true
      number:
        description: 'a number'
        default: 2


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: do a greet
        run: |
          echo "${{ github.event.inputs.number}} ${{github.event.inputs.greeting}}, ${{github.event.inputs.name}}!"
