name: PR Automation
on:
  pull_request:
    # just ready_for_review doesn't cover created nondraft PRs :(  this is stupid.
    types: [ready_for_review, opened]


jobs:
  needs-review-column:
    runs-on: ubuntu-latest

    steps:
      - name: Add to board
        env:
          #NEEDS_REVIEW_COLUMN: 7110128
          NEEDS_REVIEW_COLUMN: "MDEzOlByb2plY3RDb2x1bW4xMTAzNTA3Ng=="
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_ID: ${{ github.event.pull_request.number }}
        # TODO use a dynamic list
        if: github.event.pull_request.user.login == 'vilmibm' || github.event.pull_request.user.login == 'mislav' || github.event.pull_request.user.login == 'samcoe' || github.event.pull_request.user.login == 'ampinsk' || github.event.pull_request.user.login == 'billygriffin'
        run: |
          gh api graphql -f query="mutation { addProjectCard(input: { projectColumnId: '$NEEDS_REVIEW_COLUMN', contentId: '$PR_ID' }) { clientMutationId } }"
