name: PR Automation
on:
  pull_request:
    # just ready_for_review doesn't cover created nondraft PRs :(  this is stupid.
    types: [ready_for_review, opened]


jobs:
  needs-review-column:
    runs-on: ubuntu-latest

    steps:
      - name: Add to board
        env:
          #NEEDS_REVIEW_COLUMN: 7110128
          NEEDS_REVIEW_COLUMN: 11035076
          CONTENT_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # TODO use a dynamic list
        if: github.event.pull_request.user.login == 'vilmibm' || github.event.pull_request.user.login == 'mislav' || github.event.pull_request.user.login == 'samcoe' || github.event.pull_request.user.login == 'ampinsk' || github.event.pull_request.user.login == 'billygriffin'
        run: |
          gh api -H 'accept: application/vnd.github.inertia-preview+json' -XPOST /projects/columns/$NEEDS_REVIEW_COLUMN/cards --field 'content_url=$CONTENT_URL'
