name: get daily poem
on: workflow_dispatch
jobs:
  get-poem:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          repository: vilmibm/vilmibm
      - name: grab poem
        run: |
          tail vilmibm/README.md -n17 > poem.txt
      - name: do upload
        uses: actions/upload-artifact@v2
        with:
          name: daily-poem
          path: poem.txt
          retention-days: 1


