name: PR Automation bash redux
on:
  pull_request:
    # just ready_for_review doesn't cover created nondraft PRs :(  this is stupid.
    types: [ready_for_review, opened]

    #on:
    #  workflow_dispatch:
    #    inputs:
    #      cool:
    #        description: a cool value
    #        required: true

jobs:
  bash-redux:
    runs-on: ubuntu-latest
    steps:
      - name: bash version
        env:
          NEEDSREVIEWCOL: 7110128 # TODO update with cli/cli value
          COMMUNITYPRBOARD: "TODO" # TODO update with cli org project value
          PRURL: ${{ github.event.pull_request.html_url }}
          PRBODY: ${{ github.event.pull_request.body }}
          STAFF: "vilmibm,mislav,samcoe,billygriffin,ampinsk"
          PRAUTHOR: ${{ github.event.pull_request.user.login }}
          PRNUM: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ github.token }}
        run: |
          if echo $STAFF | grep $PRAUTHOR
          then
            gh api "projects/columns/${NEEDSREVIEWCOL}/cards -fnote='${PRURL}'"
            exit 0
          fi

          if echo $PRBODY | wc -w | grep '^[0-9]$'
          then
            gh pr comment $PRNUM -b "Thanks for the PR! We're a small team and it's helpful to have context around community submissions in order to review them appropriately. Our automation has closed this PR since the body appears to be lacking much content; please add a more descriptive PR body as well as any issues it closes and reopen. Thanks again!"
            gh pr close $PRNUM
            exit 0
          fi

          # TODO pr body word count check
          # TODO no test file changes
          # TODO no changes from pr author
          # TODO no issue mention
          # TODO not overriden by staff

          # TODO if we get this far, add to community pr board
          # - [ ] put on community PR board



